name: Searcade Login Check

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  login-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 可以选择您需要的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Run login script
        env:
          SEARCADE_ACCOUNTS: ${{ secrets.SEARCADE_ACCOUNTS }}
          TEL_TOK: ${{ secrets.TEL_TOK }}
          TEL_ID: ${{ secrets.TEL_ID }}
        run: python searcode_login.py
